/**
 * Google Gemini 2.5 Flash AI Engine
 * Intelligent Placement Management System
 */

export interface GeminiQuestion {
  id: string;
  type: "mcq" | "coding";
  subject: string;
  topic?: string;
  text: string;
  options?: string[];
  correct_answer: string;
  explanation?: string;
  points: number;
}

/**
 * Universal Gemini Chat / Reasoner
 * Routes requests through the secure backend /api/gemini endpoint
 * so GEMINI_API_KEY is never exposed to the client-side browser bundle.
 */
export async function askGemini(prompt: string, systemContext?: string): Promise<string> {
  try {
    const response = await fetch("/api/gemini", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ prompt, systemContext }),
    });

    if (response.ok) {
      const data = await response.json();
      return data.text || "No response generated by Gemini AI.";
    }

    const err = await response.json().catch(() => ({}));
    throw new Error(err.error || `Server responded with status ${response.status}`);
  } catch (error: any) {
    console.warn("Gemini backend proxy notice:", error);
    throw error;
  }
}

/**
 * AI Question Generator for Tests & Assessments
 */
export async function generateQuestionsAI(params: {
  subject: string;
  topic?: string;
  count?: number;
  type?: "mcq" | "coding";
  difficulty?: string;
}): Promise<GeminiQuestion[]> {
  const { subject, topic, count = 5, type = "mcq", difficulty = "Medium" } = params;

  const prompt = `You are a Senior Technical Assessment Lead for University Campus Recruitment.
Generate exactly ${count} high-quality ${difficulty} level ${type.toUpperCase()} assessment questions for the subject "${subject}"${topic ? ` on the topic "${topic}"` : ""}.

Return ONLY a valid JSON array of objects without markdown fences, code blocks, or preamble. Use this exact schema:
[
  {
    "id": "uuid-v4-like-string",
    "type": "${type}",
    "subject": "${subject}",
    "topic": "${topic || subject}",
    "text": "Detailed question text with clear technical context",
    ${type === "coding" ? '"correct_answer": "Complete standard working solution in clean pseudocode or JavaScript/Python"' : '"options": ["Option A text", "Option B text", "Option C text", "Option D text"],\n    "correct_answer": "A",\n    "explanation": "Brief reasoning explaining why Option A is correct"'},
    "points": 1
  }
]`;

  const raw = await askGemini(prompt);
  
  // Extract and parse JSON
  try {
    const cleaned = raw.replace(/```json/gi, "").replace(/```/g, "").trim();
    const jsonMatch = cleaned.match(/\[[\s\S]*\]/);
    const parsed = JSON.parse(jsonMatch ? jsonMatch[0] : cleaned);
    
    return parsed.map((q: any) => ({
      ...q,
      id: q.id || crypto.randomUUID(),
      type: q.type || type,
      points: q.points || 1,
    }));
  } catch (err) {
    console.error("Failed to parse Gemini questions JSON:", raw, err);
    throw new Error("Failed to format generated questions from AI. Please try again.");
  }
}

/**
 * AI Candidate Performance Analyzer & Learning Feedback
 */
export async function generateFeedbackAI(params: {
  testTitle: string;
  score: number;
  totalQuestions: number;
  wrongTopics?: string[];
}): Promise<string> {
  const { testTitle, score, totalQuestions, wrongTopics = [] } = params;

  const prompt = `A university student took the campus assessment "${testTitle}" and scored ${score} out of ${totalQuestions}.
${wrongTopics.length > 0 ? `They struggled with the following topics: ${wrongTopics.join(", ")}.` : ""}

Generate a personalized, encouraging, and structured 3-part Career & Technical Improvement Plan:
1. 🎯 **Strengths & Assessment Summary**
2. ⚠️ **Specific Concept Gaps to Review** (with actionable revision steps)
3. 🚀 **Recommended Next Steps for Campus Placement Success**

Keep the tone professional, motivating, and actionable.`;

  return await askGemini(prompt);
}
