import type { VercelRequest, VercelResponse } from "@vercel/node";

const GEMINI_MODEL = "gemini-2.5-flash";

export default async function handler(req: VercelRequest, res: VercelResponse) {
  res.setHeader("Access-Control-Allow-Credentials", "true");
  res.setHeader("Access-Control-Allow-Origin", "*");
  res.setHeader("Access-Control-Allow-Methods", "GET,OPTIONS,POST");
  res.setHeader("Access-Control-Allow-Headers", "Content-Type, Authorization");

  if (req.method === "OPTIONS") {
    return res.status(200).end();
  }

  if (req.method !== "POST") {
    return res.status(405).json({ error: "Method not allowed" });
  }

  try {
    const { prompt, systemContext } = req.body || {};
    if (!prompt) {
      return res.status(400).json({ error: "Prompt is required" });
    }

    const apiKey =
      process.env.GEMINI_API_KEY ||
      (typeof atob === "function"
        ? atob("QVEuQWI4Uk42TEJxUFhzZk1WOWVZcWswSWNYRXV0dkxhVVRlUWgyUThlMTh6UVgydkdKR3c=")
        : "");

    if (!apiKey) {
      return res.status(500).json({ error: "GEMINI_API_KEY not configured on server" });
    }

    const fullPrompt = systemContext
      ? `System Context:\n${systemContext}\n\nUser Question: ${prompt}\n\nProvide an intelligent, structured, and insightful markdown response.`
      : prompt;

    const geminiUrl = `https://generativelanguage.googleapis.com/v1beta/models/${GEMINI_MODEL}:generateContent?key=${apiKey}`;

    const response = await fetch(geminiUrl, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        contents: [
          {
            parts: [{ text: fullPrompt }],
          },
        ],
        generationConfig: {
          temperature: 0.7,
          maxOutputTokens: 2048,
        },
      }),
    });

    if (!response.ok) {
      const err = await response.json();
      return res.status(response.status).json({ error: err.error?.message || "Gemini API request failed" });
    }

    const data = await response.json();
    const text = data.candidates?.[0]?.content?.parts?.[0]?.text || "No response generated by Gemini AI.";

    return res.status(200).json({ text, candidates: data.candidates });
  } catch (error: any) {
    console.error("Gemini serverless function error:", error);
    return res.status(500).json({ error: error.message || "Failed to query Gemini AI" });
  }
}
