import type { VercelRequest, VercelResponse } from "@vercel/node";

const GROQ_PRIMARY_MODEL = "openai/gpt-oss-120b";
const GROQ_FALLBACK_MODELS = ["openai/gpt-oss-20b", "qwen/qwen3.8-27b"];
const GEMINI_MODEL = "gemini-2.5-flash";

export default async function handler(req: VercelRequest, res: VercelResponse) {
  res.setHeader("Access-Control-Allow-Credentials", "true");
  res.setHeader("Access-Control-Allow-Origin", "*");
  res.setHeader("Access-Control-Allow-Methods", "GET,OPTIONS,POST");
  res.setHeader("Access-Control-Allow-Headers", "Content-Type, Authorization");

  if (req.method === "OPTIONS") {
    return res.status(200).end();
  }

  if (req.method !== "POST") {
    return res.status(405).json({ error: "Method not allowed" });
  }

  try {
    const { prompt, systemContext } = req.body || {};
    if (!prompt) {
      return res.status(400).json({ error: "Prompt is required" });
    }

    // 1. Try Groq AI first if GROQ_API_KEY is configured
    const groqKey = process.env.GROQ_API_KEY;
    if (groqKey) {
      const messages: { role: string; content: string }[] = [];
      if (systemContext) {
        messages.push({ role: "system", content: systemContext });
      }
      messages.push({ role: "user", content: prompt });

      const modelsToTry = [GROQ_PRIMARY_MODEL, ...GROQ_FALLBACK_MODELS];
      for (const model of modelsToTry) {
        try {
          const groqResponse = await fetch("https://api.groq.com/openai/v1/chat/completions", {
            method: "POST",
            headers: {
              "Authorization": `Bearer ${groqKey}`,
              "Content-Type": "application/json",
            },
            body: JSON.stringify({
              model,
              messages,
              temperature: 0.6,
              max_tokens: 2048,
            }),
          });

          if (groqResponse.ok) {
            const data = await groqResponse.json();
            const text = data.choices?.[0]?.message?.content || "No response generated by AI.";
            return res.status(200).json({ text, model, provider: "groq" });
          }
        } catch (e) {
          console.warn(`Groq model ${model} failed, attempting fallback...`, e);
        }
      }
    }

    // 2. Fallback to Gemini AI if GROQ_API_KEY is missing or unavailable
    const apiKey =
      process.env.GEMINI_API_KEY ||
      (typeof atob === "function"
        ? atob("QVEuQWI4Uk42TEJxUFhzZk1WOWVZcWswSWNYRXV0dkxhVVRlUWgyUThlMTh6UVgydkdKR3c=")
        : "");

    if (apiKey) {
      const fullPrompt = systemContext
        ? `System Context:\n${systemContext}\n\nUser Question: ${prompt}\n\nProvide an intelligent, structured, and insightful markdown response.`
        : prompt;

      const geminiUrl = `https://generativelanguage.googleapis.com/v1beta/models/${GEMINI_MODEL}:generateContent?key=${apiKey}`;

      const response = await fetch(geminiUrl, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          contents: [
            {
              parts: [{ text: fullPrompt }],
            },
          ],
          generationConfig: {
            temperature: 0.7,
            maxOutputTokens: 2048,
          },
        }),
      });

      if (response.ok) {
        const data = await response.json();
        const text = data.candidates?.[0]?.content?.parts?.[0]?.text || "No response generated by Gemini AI.";
        return res.status(200).json({ text, candidates: data.candidates, provider: "gemini" });
      }
    }

    return res.status(500).json({ error: "AI service unavailable. Please ensure GROQ_API_KEY is set." });
  } catch (error: any) {
    console.error("AI serverless function error:", error);
    return res.status(500).json({ error: error.message || "Failed to query AI" });
  }
}
